### ISSUE TITLE
Direct synctex

### ISSUE THREAD

**Issue by aviatesk** [Aerijo/atom-pdf-view-plus#2]
Hi @Aerijo !

I'm using this package for previewing my LaTeX documents, and currently every time I rebuild a ducument, a PDF view gets refreshed and the position gets automatically scrolled up to the top.

I think we can circumvent this if we have direct synctex feature which works with this package.
Do you have any idea to implement this ?

**Comment by Aerijo** [comment]
Hmm, I tried it just now and it seemed to stay at the same position after the reload. Do you have steps to reproduce?

**Comment by aviatesk** [comment]
Sure.

My steps to repro:
1. Rebuild a latex document using [latex](https://github.com/thomasjo/atom-latex) package
2. (maybe just after rebuilding the document has been finished) the error below shown
![image](https://user-images.githubusercontent.com/40514306/72714364-effff280-3bb1-11ea-9b63-51d9cb401f55.png)
3. the document gets refreshed after all, but the page is no longer the same as before (always scrolled up to the top)

FYI:
latex config:
```coffee
latex:
    enableShellEscape: true
    engine: "uplatex"
    openResultAfterBuild: false
    useRelativePaths: true
```

pdf-view-plus config:
```coffee
"pdf-view-plus":
    enableSynctex: true
```

Thanks so much for your help ! (and also for your great latex-related packages as well :))

**Comment by Aerijo** [comment]
Sorry for the delay, I figured this was related to large projects loading and I didn't have one on hand. pdftex appears to stream the results to the PDF file (which makes sense I guess; you don't want the file size limited by your RAM), but it means the PDF is in an invalid state while being built. That's also why it says an error occurred in the banner.

I think v1.10.0 should fix this issue, and it also allows you to configure the debounce.

**Comment by aviatesk** [comment]
No worries, thanks for taking your time to fix this !
Well, v1.10.0 still shows an error banner at the end of building (even with a different range of debounces), but the refreshed page remains to be the same as the previous one, so the problem is kinda fixed, thanks.

**Comment by Aerijo** [comment]
> even with a different range of debounces

You need to close and reopen the PDF tab to get the change to apply, I hadn't got around to detecting the config change just yet.

> Well, v1.10.0 still shows an error banner at the end of building

Even when it finishes loading? I haven't been able to get the error banner, but I've seen other issues that mention it. I don't know if I can fix it directly here, as the open method first closes the existing PDF before opening the new one, but I eventually plan to add support to `latex` to trigger the reload of the PDF itself after the build finishes, instead of detecting changes on disk.

Also, could you show what 'More information' says?

**Comment by aviatesk** [comment]
> You need to close and reopen the PDF tab to get the change to apply, I hadn't got around to detecting the config change just yet.

ah, I get it ! And yeah, increasing debouncing got rid of the error :tada:

> Even when it finishes loading?

Nope, the banner just showed up at the end of building, and then disappeared.
Now I don't have any error banner though.

**Comment by aviatesk** [comment]
And because I just proposed direct synctex in order to circumvent the issue. I will close this, while direct synctex feature would be very useful though.
Thanks @Aerijo !
